feat(pages): update entry
vatesfr/mini-safe pull request #20
Opened 2018-10-24 07:56 UTC by heafalan

Fixes #15

2018-10-24 08:30 UTC, julien-f requested changes
IMHO editing is not obvious with your design, I think it would be better to:
- click on an icon next to the item to make it editable
- edit the item in the form
- submit the form to save the changes

2018-10-25 09:41 UTC, heafalan commented
This version of updateEntry() returns an error.
"TypeError: NetworkError when attempting to fetch resource."
I don't know why sometimes it works and sometimes not, 
and even if the data is updated, the error is returned.

Maybe I have to change the way I use the form ?

2018-10-25 09:46 UTC, julien-f commented on packages/pages/package-lock.json
> +          "optional": true
Please remove this changes, they are introduced by  `npm` but are not relevant for this PR.

2018-10-25 10:15 UTC, julien-f commented on packages/pages/package-lock.json
> +          "optional": true
Still relevant.

2018-10-25 10:16 UTC, julien-f commented on packages/pages/src/App.js
> +    isEditting: false,
You don't need this field, you could simply detect edition based on whether `state.id` is `""`.

2018-10-25 10:17 UTC, julien-f commented on packages/pages/src/App.js
> +        </label>
It would be easier to use if the inputs initially contain the current values.

2018-10-25 10:17 UTC, julien-f commented on packages/pages/src/App.js
> +      <form onSubmit={effects.submitUpdates}>
Good idea to use a form, it's more semantic and allows the user to submit simply by using the *Enter* key. :+1:

2018-10-25 10:18 UTC, julien-f commented on packages/pages/src/App.js
> +      </form>
You could merge this form with the *creation* form.

2018-10-25 12:02 UTC, julien-f commented on packages/pages/package-lock.json
> +          "optional": true
Still not fixed.

2018-10-25 12:12 UTC, julien-f commented on packages/pages/src/App.js
> +                )}
Avoid creating functions (that's what `bind` does) in the rendering function, you can use [`data-*`](https://devdocs.io/html/attributes#data-attribute) to associate value with the `<button>`.

Even in this case, you should probably only attach the `id` and fetch the rest of the data directly in the state.

2018-10-25 12:13 UTC, julien-f commented on packages/pages/src/App.js
> +      this.state.id = "";
You should only reset the state if the entry was successfully updated.

2018-10-25 13:39 UTC, julien-f commented on packages/pages/src/App.js
> +      <fieldset>
Why `<fieldset>`?

2018-10-25 13:39 UTC, julien-f commented on packages/pages/src/App.js
> +        )}
Lot of duplicated code, don't you think it would be possible to mutualize?

2018-10-25 14:30 UTC, julien-f commented on packages/pages/src/App.js
> +    async updateEntry(_, event) {
Why `async`?

2018-10-25 14:31 UTC, julien-f commented on packages/pages/src/App.js
> +    },
https://devdocs.io/dom/htmlelement/dataset

```js
const  { dataset } = event.target

this.state.id = dataset.id
this.state.name = dataset.name
this.state.content = dataset.content
```

2018-10-25 14:33 UTC, julien-f commented on packages/pages/src/App.js
> +    },
`createEntry` and `submitUpdates` share a lot of code/behavior, don't think it should be possible to unite them?

2018-10-26 09:14 UTC, julien-f commented on packages/pages/src/App.js
> +        <button type="submit" value="Submit">
`value` is unused, you can remove it.

2018-10-26 09:15 UTC, julien-f commented on packages/pages/src/App.js
> +      </form>
You should add a *Reset* button to:
- empty the fields
- cancel the edition if any

2018-10-26 09:18 UTC, julien-f commented on packages/pages/src/App.js
> +      }
You can mutualize even more code:

```js
const { state } = this
const { id, name, content } = state
const response = await fetch("/api/", {
  method: "post",
  body: format.request(0, id === "" ? "createEntry" : "updateEntry", {
    id: id === "" ? undefined : id,
    name,
    content,
  }
})
```

2018-10-26 09:19 UTC, julien-f commented on packages/pages/src/App.js
> +      const parsed = parse(await response.text());
You should use the new `parse.result` (you may need to update `json-rpc-protocol|).

2018-10-26 09:19 UTC, julien-f commented on packages/pages/src/App.js
> +    },
Don't forget this comment.

2018-10-26 14:52 UTC, julien-f approved these changes
Nice PR :+1:

2018-10-26 14:53 UTC, merged